updated github file

diff --git a/.github/workflows/main_pluto-frontend.yml b/.github/workflows/main_pluto-frontend.yml
--- a/.github/workflows/main_pluto-frontend.yml
+++ b/.github/workflows/main_pluto-frontend.yml
@@ -25,11 +25,15 @@ jobs:
 
       - name: Install dependencies
         run: |
+          pwd
           ls -la
+          ls -la public/ || echo "public directory not found"
           npm ci
 
       - name: Build React app
         run: |
+          pwd
+          ls -la public/
           REACT_APP_API_URL=https://pluto-backend-chaqffgxhrbnh0cv.norwayeast-01.azurewebsites.net npm run build
 
       - name: Upload artifact for deployment job
